### ISSUE TITLE
Value should be a JSON!

### ISSUE THREAD

**Issue by lexcorp** [cboyer/mirth-zabbix#3]
In discovery rules I get this error:

Value should be a JSON object.

![image](https://user-images.githubusercontent.com/5751288/143283844-aeb9280c-5d5d-451d-bcff-688dd43da54d.png)

**Comment by cboyer** [comment]
Probably an unauthorized character in JSON from a connector/channel name.
Get your JSON with:
- `zabbix_get.exe -s YOUR_MIRTH_IP -p MIRTHIX_PORT -k mirth.discovery.channel`
- `zabbix_get.exe -s YOUR_MIRTH_IP -p MIRTHIX_PORT -k mirth.discovery.connector`

Don't forget to allow your IP to query Mirthix (cf. README). 
You can parse it with online tools or paste it here so I can inspect data and publish a fix to escape or filter some characters.
You can get `zabbix_get.exe` at https://www.zabbix.com/download_agents (archive).

**Comment by lexcorp** [comment]
I get this message:

_**zabbix_get.exe [10980]: Check access restrictions in Zabbix agent configuration**_

**Comment by cboyer** [comment]
Did you allowed your IP in Mirthix to be able to query the channel? (Source Filter > Rule Builder)
What's the Mirth and Zabbix version?

**Comment by lexcorp** [comment]
Mirth version: 3.7.1
Zabbix version: 4.0.22

**Comment by lexcorp** [comment]
> 

![image](https://user-images.githubusercontent.com/5751288/152647799-c5b7366a-57c3-42c5-831f-72aab81554f7.png)

**Comment by cboyer** [comment]
Change value 127.0.0.1 to your Zabbix server IP, save and redeploy channel.
